name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

  repository_dispatch:
    types: [backend_post] 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Send Slack Notification (Start)
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "C0AUJ33K0MV",
              "text": "🚀 *Deploying to GH Pages...*\nUser: ${{ github.actor }}\nCommit: ${{ github.event.head_commit.message }}"
            }


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          

      - name: Install dependencies
        run: npm ci
        working-directory: churchblog

      - name: Build project
        run: npm run build
        working-directory: churchblog

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist
  deploy:
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      needs: build
      steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          # Adding @channel or your Slack ID helps trigger mobile alerts
          SLACK_MESSAGE: "<!channel> Build and Deploy successful! 🚀"
          SLACK_COLOR: ${{ job.status }}

      - name: Send Slack Notification (Success)
        if: success()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "C0AUJ33K0MV",
              "text": "<!here> ✅ *Success!* The site is live at: ${{ steps.deployment.outputs.page_url }}"
            }

      - name: Send Slack Notification (Failure)
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "C0AUJ33K0MV",
              "text": "<!channel> ❌ *Build Failed!* Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }